name: 'Upload app to TestFlight'
description: 'Uploads an app to Apple TestFlight'
author: 'Itty Bitty Apps Pty Ltd'
inputs:
  app-path:
    description: 'The path to the app (ipa etc)'
    required: true
  app-type:
    description: 'The type of app to upload (osx | ios | appletvos)'
    required: true
    default: 'ios'
  issuer-id:
    description: 'The AppStoreConnect API Key Issuer Identifier'
    required: false
  api-key-id:
    description: 'The Key ID for AppStore Connect API'
    required: false
  api-private-key:
    description: 'The PKCS8 format Private Key for AppStore Connect API'
    required: false
  testflight-email:
    description: 'The AppstoreConnect Email addess'
    required: true
  testflight-password:
    description: 'The AppstoreConnect password'
    required: true
outputs:
  altool-response:
    description: 'XML output from altool'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
